### ISSUE TITLE
NS3仿真时的切换问题

### ISSUE THREAD

**Issue by xieflynext** [silent-rookie/Dynamic_Load_Balancing_Routing_Algorithm#3]
你好，我在代码中看ns3--sat-sim.没有看到低轨和地面的移动性切换和低轨和高轨的移动性切换，我看到在 TopologySatelliteNetwork类中建立了网络拓扑结构中。但是貌似并没有有后续切换的操作。想请问一下移动性切换这部分是如何实现的？谢谢

**Comment by silent-rookie** [comment]
您好，该项目是基于Hypatia这个框架搭建的，该框架构建与ns3之上，并提供了便捷的生成和模拟卫星网络的能力，您可以通过这篇文章了解详细信息：《Exploring the “Internet from space” with Hypatia》by  Simon Kassing∗, Debopam Bhattacherjee∗, André Baptista Águas, Jens Eirik Saethre, Ankit Singla ETHZürich
    回到您说的这个切换的问题，该框架的解决思路是：在每个时间间隔（默认应该是几十毫秒，我有点记不清了），通过当前卫星网络（地面站，低轨卫星网络，高轨卫星网络）的信息，利用python代码计算每个时刻这些节点的位置，然后将这些位置信息保存在一个文件中；之后ns3这边通过读取这个位置文件，就知道了每个时刻各个节点的位置信息。所以实际上在ns3的代码中，我们能清晰的知道每个节点的位置，所以切换策略非常简单：只要计算两个节点之间的直线距离有没有超出可能的最大距离（例如，两颗低轨卫星的最大距离的直线与地球表面相切）就能知道两个节点之间还能不能建立连接了。
    **最后在本项目中，如果地面站与低轨卫星之间的距离超出最大距离，则我们切换地面站的连接到距离其最近的低轨卫星上。低轨卫星与高轨卫星的连接同理。但是低轨卫星之间的连接，如果超出最大距离，本项目的策略是：不切换低轨卫星之间的连接，而是暂时断开两颗低轨卫星的连接，等到小于最大距离时才重新建立连接。这也是参考了上面提到的这篇论文的观点：低轨卫星之间的频繁切换不利于卫星网络的稳定，因为在实际场景中，卫星之间建立连接也是需要时间的。

**Comment by xieflynext** [comment]
非常感谢您的回答，明白了。
